services:
  tax-db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - tax-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tax
    healthcheck:
      test: pg_isready -U postgres -d tax -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 3
  tax:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://tax-db:5432/tax
      - SPRING_FLYWAY_URL=jdbc:postgresql://tax-db:5432/tax
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
    healthcheck:
      test: wget -qO - http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      tax-db:
        condition: service_healthy
  tax-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "tax",
      "--app-port", "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:tax"
volumes:
  tax-db-data:
