name: Update GraphQL schema

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  schema:
    name: Update GraphQL schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: actions/checkout@v4
        with:
          repository: "misarch/schemas"
          path: "schemas"
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Save graphql schemas
        run: |
          chmod +x ./scripts/generate-graphql-schema.sh
          ./scripts/generate-graphql-schema.sh
      - uses: misarch/graphql-schema-transform@v1
        with:
          schema: schemas/tax.graphql
          target: schemas/tax.graphql
      - uses: peter-evans/create-pull-request@v6
        with:
          path: ./schemas
          commit-message: Update tax schema
          branch: update/tax
          token: ${{ secrets.SCHEMAS_PUSH_SECRET }}
